### PR TITLE
runtime: Fsync when saving graph changes

### LINKED ISSUE #60: Coordinator auto-save keeps emitting errors
It seems it saves the graph changes at least once (see #59), but I see a lot of errors like:

```
Failed to save graph file { Error: ENOENT: no such file or directory, rename 'graphs/c-base.jsonmsgflo-autosave-1485431633916' -> 'graphs/c-base.json'                                         errno: -2,                                                                                                                                                                                          code: 'ENOENT',                                                                                                                                                                                     syscall: 'rename',                                                                                                                                                                                  path: 'graphs/c-base.jsonmsgflo-autosave-1485431633916',                                                                                                                                            dest: 'graphs/c-base.json' }                            
```

Also, subsequent graph edits in live mode like changing edge metadata don't get persisted.

### PR DESCRIPTION
**Pull request by jonnor**
Hopefully fixes #60

### CODE REVIEW

**Comment by bergie** [comment]
Still seeing the same error. With some added debugging, I'm seeing tons of writes nearly simultaneously. So one potential help would be to debounce

**Comment by jonnor** [comment]
Yes writing is on every graph change. Which is mostly fine when user-driven, but when Flowhub connects and sends its state its gonna be hell. Tried to add some debounce logic now

**Comment by jonnor** [comment]
Autosave code could use a test or two :)

**Comment by bergie** [comment]
Verified: with the latest version not seeing the errors any longer. Though, also not seeing #59 so maybe it is never run now?

**Comment by jonnor** [comment]
@bergie `export DEBUG=msgflo:runtime*` and you should see some `saving graph` messages

**Comment by bergie** [comment]
@jonnor nope, not seeing any, only _enabling autosave_

**Comment by jonnor** [comment]
Yeah I know why

**Comment by jonnor** [comment]
Slightly better chance of working now. Still programming blind though so no guarantees...

**Comment by bergie** [comment]
OK, seeing saves happening now, and at a lot less crazy pace

**Comment by jonnor** [comment]
We can bump the debounce rate later,if it is needed.

**Pull request merged**
